### ISSUE TITLE
[dx] an invalid signature call to a transformation should probably be unrecoverable, thus stopping the whole job.

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#172]
```
TypeError (in PickleWriter)
 | Write() got an unexpected keyword argument 'foo'
 |
 | Traceback (most recent call last):
 |   File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/execution/node.py", line 88, in loop
 |     self.step()
 |   File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/execution/node.py", line 111, in step
 |     self.handle_results(input_bag, input_bag.apply(self._stack))
 |   File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/structs/bags.py", line 63, in apply
 |     return func_or_iter(*args, *self.args, **kwargs, **self.kwargs)
 |   File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/config/processors.py", line 85, in __call__
 |     return self.wrapped(*self.context, *args, **kwargs)
 |   File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/nodes/io/base.py", line 80, in __call__
 |     return self.write(*args, **kwargs)
 | TypeError: write() got an unexpected keyword argument 'foo'
```

**Comment by hartym** [comment]
In 0.6
