### ISSUE TITLE
[cli] bonobo init should work on an empty existing directory

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#187]
```
$ bonobo init .
Traceback (most recent call last):
  File "/Users/rd/bdk/.virtualenvs/3.6/bin/bonobo", line 11, in <module>
    load_entry_point('bonobo', 'console_scripts', 'bonobo')()
  File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/commands/__init__.py", line 35, in entrypoint
    commands[args.pop('command')](**args)
  File "/Users/rd/Projects/bonobo-devkit/bonobo/bonobo/commands/init.py", line 13, in execute
    checkout=branch
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/main.py", line 91, in cookiecutter
    output_dir=output_dir
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/generate.py", line 269, in generate_files
    overwrite_if_exists
  File "/Users/rd/bdk/.virtualenvs/3.6/lib/python3.6/site-packages/cookiecutter/generate.py", line 209, in render_and_create_dir
    raise OutputDirExistsException(msg)
cookiecutter.exceptions.OutputDirExistsException: Error: "." directory already exists
```

**Comment by hartym** [comment]
I changed the way it works for 0.6, we will drop cookiecutter because we don't want anymore those "pseudo packages" in which python import mechanism can't work without hacks & magic.

New recommended way will be either a file, or a full python package.
