### ISSUE TITLE
[dx] Better error messages for configurables

### ISSUE THREAD

**Issue by hartym** [python-bonobo/bonobo#200]
```
TypeError (in Select)
 | Call() takes 2 positional arguments but 3 were given
 |
 | Traceback (most recent call last):
 |   File "/Users/rd/Work/Bonobo/.virtualenvs/3.6/lib/python3.6/site-packages/bonobo/execution/node.py", line 90, in loop
 |     self.step()
 |   File "/Users/rd/Work/Bonobo/.virtualenvs/3.6/lib/python3.6/site-packages/bonobo/execution/node.py", line 113, in step
 |     self.handle_results(input_bag, input_bag.apply(self._stack))
 |   File "/Users/rd/Work/Bonobo/.virtualenvs/3.6/lib/python3.6/site-packages/bonobo/structs/bags.py", line 68, in apply
 |     return func_or_iter(*args, *self.args, **kwargs, **self.kwargs)
 |   File "/Users/rd/Work/Bonobo/.virtualenvs/3.6/lib/python3.6/site-packages/bonobo/config/processors.py", line 85, in __call__
 |     return self.wrapped(*self.context, *args, **kwargs)
 |   File "/Users/rd/Work/Bonobo/.virtualenvs/3.6/lib/python3.6/site-packages/bonobo/config/configurables.py", line 194, in __call__
 |     return self.call(*args, **kwargs)
 | TypeError: call() takes 2 positional arguments but 3 were given
```

(happens when a transformation get wrongly-shapped bag as its input)

**Comment by hartym** [comment]
Better in 0.6, let's see if enough.
