### ISSUE TITLE
Tutorial 2 raises ValueError

### ISSUE THREAD

**Issue by mpenkov** [python-bonobo/bonobo#206]
```
(bonobo)bash-3.2$ bonobo run -m bonobo.examples.tutorials.tut02e02_write
Traceback (most recent call last):
  File "/Users/misha/envs/bonobo/bin/bonobo", line 11, in <module>
    load_entry_point('bonobo', 'console_scripts', 'bonobo')()
  File "/Users/misha/pyconde17/bonobo/bonobo/commands/__init__.py", line 35, in entrypoint
    commands[args.pop('command')](**args)
  File "/Users/misha/pyconde17/bonobo/bonobo/commands/run.py", line 154, in execute
    filename, module, install, quiet, verbose, default_env_file, default_env, env_file, env
  File "/Users/misha/pyconde17/bonobo/bonobo/commands/run.py", line 88, in read
    context = runpy.run_module(module, run_name='__bonobo__')
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 208, in run_module
    return _run_code(code, {}, init_globals, run_name, mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/misha/pyconde17/bonobo/bonobo/examples/tutorials/tut02e02_write.py", line 12, in <module>
    'coffeeshops.json', fs='fs.output', ioformat='arg0'
  File "/Users/misha/pyconde17/bonobo/bonobo/config/configurables.py", line 170, in __init__
    setattr(self, name, value)
  File "/Users/misha/pyconde17/bonobo/bonobo/config/options.py", line 80, in __set__
    inst._options_values[self.name] = self.clean(value)
  File "/Users/misha/pyconde17/bonobo/bonobo/config/options.py", line 109, in clean
    format(self.name, self.value)
ValueError: Removed options cannot change value, 'ioformat' must now be 'kwargs' (and you should remove setting the value explicitely, as it is deprecated and will be removed quite soon.
```

The offending line appears to be:

```
bonobo.JsonWriter('coffeeshops.json', fs='fs.output', ioformat='arg0')
```

The error message is helpful (although it does have a typo, s/explicitely/explicitly) but it isn't obvious how to proceed.

```
bonobo.JsonWriter('coffeeshops.json', fs='fs.output', kwargs='arg0'),
```

gives us:

```
TypeError: JsonWriter() got 1 unexpected option: 'kwargs'.
```

and

```
bonobo.JsonWriter('coffeeshops.json', fs='fs.output', kwargs={'ioformat': 'arg0'})
```

gives us:

```
TypeError: JsonWriter() got 1 unexpected option: 'kwargs'.
```

**Comment by hartym** [comment]
This error is normal using the develop version, as I worked toward simplification of input/output of nodes. From 0.6, nodes only support one input/output format, which is related to the kind of data they are using.

All nodes that work with "tuple-like" data are using args, all nodes that use dict-like (or key-value) input/output now use kwargs.

So, yes, ioformat='arg0' is offending and there should not be any ioformat= kwarg anymore, although the enforced one is still supported (plan to remove it in 0.7).
