### ISSUE TITLE
bonobo init failed

### ISSUE THREAD

**Issue by hvnsweeting** [python-bonobo/bonobo#235]
I'm using 

```
 $ bonobo version
bonobo v.0.6.0 (in /media/media/py35env/lib/python3.5/site-packages)
```

Got error 

```
$ bonobo init my-etl-err
CRIT:0000:root: Uncaught exception (in thread 140395635795712).
│ Traceback (most recent call last):
│   File "/home/hvn/py35env/bin/bonobo", line 11, in <module>
│     sys.exit(entrypoint())
│   File "/home/hvn/py35env/lib/python3.5/site-packages/bonobo/commands/__init__.py", line 59, in entrypoint
│     command(**parsed_args)
│   File "/home/hvn/py35env/lib/python3.5/site-packages/bonobo/commands/init.py", line 74, in handle
│     self.create_file_from_template(template=template, filename=filename)
│   File "/home/hvn/py35env/lib/python3.5/site-packages/bonobo/commands/init.py", line 24, in create_file_from_template
│     raise ValueError('Filenames should end with ".py".')
└ ValueError  Filenames should end with ".py".
```

**Comment by hartym** [comment]
The behaviour changed in 0.6. You need to run "bonobo init somejob.py".

The documentation will be updated as soon as possible.

**Comment by hartym** [comment]
Documentation updated, https://www.bonobo-project.org/how-to/bootstrap
