### ISSUE TITLE
Got Filename should end with .py error when do bonobo init

### ISSUE THREAD

**Issue by qinfeng** [python-bonobo/bonobo#246]
Just installed bonobo with pip3 install bonobo

However got below error when do my first bonobo init
```
➜  testproj bonobo init my-etl-job                                                                                                                       11:37
CRIT:0001:root: Uncaught exception (in thread 140735690740544).
│ Traceback (most recent call last):
│   File "/usr/local/bin/bonobo", line 11, in <module>
│     sys.exit(entrypoint())
│   File "/usr/local/lib/python3.6/site-packages/bonobo/commands/__init__.py", line 59, in entrypoint
│     command(**parsed_args)
│   File "/usr/local/lib/python3.6/site-packages/bonobo/commands/init.py", line 74, in handle
│     self.create_file_from_template(template=template, filename=filename)
│   File "/usr/local/lib/python3.6/site-packages/bonobo/commands/init.py", line 24, in create_file_from_template
│     raise ValueError('Filenames should end with ".py".')
└ ValueError  Filenames should end with ".py".
➜  testproj bonobo version                                                                                                                            1s 903ms
bonobo v.0.6.1 (in /usr/local/lib/python3.6/site-packages)
```

OS: macOS high serria

**Comment by hartym** [comment]
`$ bonobo init my-etl-job.py
`
Should solve it. Since this is the second time this issue is opened, can you tell me what part of the docs made it unclear ? Or how can we improve the error message ?

TY

**Comment by hartym** [comment]
Ha, got it, I did not update https://www.bonobo-project.org/getting-started after 0.6. Will do.

**Comment by hartym** [comment]
Updated.
